export const BlogCategories: string[] = [
  "Breaking News",
  "Company News & Announcements",
  "Regional Construction Updates",
  "Construction News & Updates",
  "Basements & Groundworks",
  "Civils & Infrastructure",
  "Sub-Structure & Superstructure",
  "Structural Engineering & RC Works",
  "Shell & Core / Cut & Carve Projects",
  "Steel & Timber Structures",
  "Extensions & Alterations",
  "Demolition & Enabling Works",
  "Roofing & External Works",
  "Interior Fit-Out & Finishes",
  "Stairs, Joinery & Carpentry",
  "Landscaping & External Features",
  "Design, Architecture & Compliance",
  "Case Studies & Project Insights",
  "Construction Guides & FAQs",
  "Industry Insights & Trends",
  "Research & Innovation",
  "Features & Thought Leadership"
]