export const Subjects: string[] = [
    "Accounting",
    "Automotive",
    "Architecture",
    "Business",
    "Biology",
    "Case Study",
    "Communication",
    "Cultural Studies",
    "Childcare",
    "Criminology",
    "Corporate Strategy",
    "Computer Science",
    "Economics",
    "Education",
    "Engineering",
    "Environmental Studies",
    "English Literature",
    "Employee Reactions",
    "Enterpreneurship",
    "Fashion",
    "Finance",
    "Food Safety Management",
    "General Studies",
    "Health",
    "Hospitality",
    "Human Resource Management",
    "Human Rights",
    "Health & Social Care",
    "Information Technology",
    "Information Systems",
    "International Studies",
    "Industrial Relation",
    "Innovation and Commercialisation",
    "Law",
    "Leadership",
    "Logistics and Supply Chain Management",
    "Leadership and Management",
    "Management",
    "Marketing",
    "Mathematics",
    "Media",
    "Medical",
    "Music",
    "Nursing",
    "Networking",
    "Organisational Behaviour",
    "Project Management",
    "Psychology",
    "Politics",
    "Personal and Professional Development",
    "Planning for Growth",
    "Religion",
    "Research Methodologies",
    "Sociology",
    "Social Work",
    "Social Policy",
    "Sciences",
    "Social media",
    "Statistics",
    "Tourism",
    "Teaching",
    "Understanding Self and others"
]